[project]
name = "moe-lgf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.5.0",
    "ollama>=0.6.1",
    "transformers>=5.1.0",
]
